# Generated by Django 3.1.7 on 2021-04-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0002_auto_20210401_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shop_order_id',
        ),
    ]
