# Generated by Django 3.1.7 on 2021-04-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0004_auto_20210405_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='storehouse.Genre', verbose_name='genre'),
        ),
    ]
