# Generated by Django 3.1.7 on 2021-03-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0006_remove_bookinstance_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=20, verbose_name='order date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Waiting'), (2, 'In progress'), (3, 'Done'), (4, 'Rejected')], default=1, help_text='Order status'),
        ),
    ]
