version: "3.8"

services:
  db:
    container_name: db
    image: postgres
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - webnet
    expose:
      - 5432
    env_file: ./config/.env
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123123'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    networks:
      - webnet
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  warehouse: &warehouse
    container_name: warehouse
    env_file: ./config/.env
    build:
      target: development_build
      args:
        DJANGO_ENV: 'dev'
    volumes:
      - ./warehouse:/code
      - ./config:/config
    environment:
      DJANGO_DEBUG: 1
      DATABASE_HOST: 'db'
    command: sh /runserver.sh


  shop: &shop
    container_name: shop
    env_file: ./config/.env
    build:
      target: development_build
      args:
        DJANGO_ENV: 'dev'
    volumes:
      - ./shop:/code
      - ./config:/config
    environment:
      DJANGO_DEBUG: 1
      DATABASE_HOST: 'db'
    command: sh /runserver.sh


  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    command: [ "-smtp-bind-addr", "0.0.0.0:25" ]
    user: root
    restart: on-failure
    networks:
      - webnet
      - nginx_network
    expose:
      - 25
      - 8025
    healthcheck:
      test: [ "CMD", "echo", "|", "telnet", "127.0.0.1 25" ]
      interval: 10s
      timeout: 5s
      retries: 5


  nginx:
    container_name: nginx
    build:
      target: development_build
    ports:
      - 8025:8025
      - 5555:5555
    depends_on:
      - mailhog

volumes:
  db-data: