version: "3.8"

services:

  warehouse: &warehouse
    container_name: warehouse
    env_file: ./config/.env
    build:
      target: development_build
      args:
        DJANGO_ENV: 'dev'
    volumes:
      - ./backend_warehouse:/code
      - ./config:/config
    environment:
      DJANGO_DEBUG: 1
    command: sh /runserver.sh


  shop: &shop
    container_name: shop
    env_file: ./config/.env
    build:
      target: development_build
      args:
        DJANGO_ENV: 'dev'
    volumes:
      - ./backend_shop:/code
      - ./config:/config
    environment:
      DJANGO_DEBUG: 1
    command: sh /runserver.sh
