# Generated by Django 3.1.7 on 2021-03-28 19:30

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('author', models.CharField(max_length=200, verbose_name='author')),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000, verbose_name='summary')),
                ('isbn', models.CharField(help_text='13 character ISBN number', max_length=13, verbose_name='ISBN')),
                ('language', models.CharField(max_length=20, verbose_name='language')),
                ('genre', models.CharField(max_length=200, verbose_name='genre')),
                ('price', models.FloatField(help_text='Book price', max_length=20, verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this order across whole library', primary_key=True, serialize=False)),
                ('customer_mail', models.EmailField(help_text='Customer e-mail address', max_length=254, verbose_name='customer mail')),
                ('order_date', models.DateField(help_text='Date when order was created', verbose_name='order date')),
                ('shipped_date', models.DateField(help_text='Date when order moved to Done status', verbose_name='shipped date')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Waiting'), (2, 'In progress'), (3, 'Sent'), (4, 'Done'), (5, 'Rejected')], default=2, help_text='Order status')),
                ('comment', models.CharField(blank=True, max_length=20, verbose_name='order date')),
            ],
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Books quantity', verbose_name='quantity')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.book')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
            ],
        ),
    ]
