# Generated by Django 3.1.7 on 2021-03-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author', 'price']},
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=models.DateField(blank=True, help_text='Date when order moved to Done status', verbose_name='shipped date'),
        ),
    ]
