# Generated by Django 3.1.7 on 2021-03-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210328_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=models.DateField(help_text='Date when order moved to Done status', null=True, verbose_name='shipped date'),
        ),
    ]
