# Generated by Django 3.1.7 on 2021-03-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210328_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=20, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=models.DateField(blank=True, help_text='Date when order moved to Done status', null=True, verbose_name='shipped date'),
        ),
    ]
