# Generated by Django 3.1.7 on 2021-03-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_mail',
        ),
    ]
